name: Release
"on":
  push:
    branches:
      - master
jobs:
  publish-gpr:
    name: publish-gpr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@debjitpk'
      - run: npm install
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}